/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 13-abr.-2020 6:17:41 p. m. 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS Banco CASCADE
;

DROP TABLE IF EXISTS biometria CASCADE
;

DROP TABLE IF EXISTS cliente CASCADE
;

DROP TABLE IF EXISTS Formas_pago CASCADE
;

DROP TABLE IF EXISTS Giros CASCADE
;

DROP TABLE IF EXISTS Locutorio CASCADE
;

DROP TABLE IF EXISTS "Negociacion " CASCADE
;

DROP TABLE IF EXISTS pais CASCADE
;

DROP TABLE IF EXISTS tipo_cliente CASCADE
;

DROP TABLE IF EXISTS tipo_documento CASCADE
;

DROP TABLE IF EXISTS ubicacion CASCADE
;

/* Drop Sequences */

DROP SEQUENCE  IF EXISTS  biometria_set  CASCADE
;

/* Create Sequences */

INCREMENT 1
start 0
;

/* Create Tables */

CREATE TABLE Banco
(
	id_Banco varchar(50) NOT NULL,
	Origen_giro varchar(50) NOT NULL,
	Destino_giro varchar(50) NOT NULL,
	Monto_giro varchar(50) NOT NULL
)
;

CREATE TABLE biometria
(
	huella_digital_1 bytea NULL,
	huella_digital_2 bytea NULL,
	id_biometria numeric(20) NOT NULL,
	id_cliente varchar(5) NULL
)
;

CREATE TABLE cliente
(
	id_cliente varchar(5) NOT NULL,
	nombre varchar(30) NULL,
	apellidos varchar(30) NULL,
	razon_social varchar(30) NULL,
	id_tipo_documento varchar(5) NULL,
	id_biometria numeric(20) NULL,
	id_pais varchar(50) NULL,
	id_tipo_cliente varchar(50) NULL,
	id_ubicacion varchar(50) NULL,
	id_giro varchar(50) NULL
)
;

CREATE TABLE Formas_pago
(
	id_forma_pago varchar(50) NOT NULL
)
;

CREATE TABLE Giros
(
	id_giro integer NOT NULL,
	id_cliente integer NOT NULL,
	Valor_Giro varchar(50) NOT NULL
)
;

CREATE TABLE Locutorio
(
	id_locutorio varchar(50) NOT NULL,
	direccion varchar(50) NOT NULL,
	telefono varchar(50) NOT NULL,
	email varchar(50) NOT NULL,
	id_giro integer NULL
)
;

CREATE TABLE "Negociacion "
(
	Id_negociacion varchar(50) NOT NULL,
	Id_Banco varchar(50) NOT NULL,
	Origen varchar(50) NOT NULL,
	Destino varchar(50) NOT NULL,
	Vigencia_Envio integer NOT NULL,
	Flete integer NOT NULL,
	Comision_Giro varchar(50) NOT NULL,
	id_pais varchar(50) NOT NULL
)
;

CREATE TABLE pais
(
	nombre varchar(50) NOT NULL,
	gentilicio varchar(50) NOT NULL,
	UPS_pais varchar(50) NOT NULL,
	region varchar(50) NOT NULL,
	ciudad varchar(50) NOT NULL,
	Convencion_Pais varchar(50) NOT NULL,
	Id_negociacion varchar(50) NOT NULL,
	Zona_Horaria varchar(50) NOT NULL
)
;

CREATE TABLE tipo_cliente
(
	id_tipo_cliente varchar(50) NOT NULL,
	nombre varchar(50) NULL
)
;

CREATE TABLE tipo_documento
(
	id_tipo_documento varchar(5) NOT NULL,
	nombre_documento varchar(50) NULL,
	id_cliente varchar(5) NULL
)
;

CREATE TABLE ubicacion
(
	id_ubicacion varchar(50) NOT NULL,
	direccion varchar(50) NOT NULL,
	id_cliente varchar(5) NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE Banco ADD CONSTRAINT PK_Table1
	PRIMARY KEY (id_Banco)
;

ALTER TABLE biometria ADD CONSTRAINT PK_huella_digital
	PRIMARY KEY (id_biometria)
;

CREATE INDEX IXFK_biometria_cliente ON biometria (id_cliente ASC)
;

ALTER TABLE cliente ADD CONSTRAINT PK_cliente
	PRIMARY KEY (id_cliente)
;

CREATE INDEX IXFK_cliente_biometria ON cliente (id_biometria ASC)
;

CREATE INDEX IXFK_cliente_cliente ON cliente (id_cliente ASC)
;

CREATE INDEX IXFK_cliente_Giros ON cliente (id_giro ASC)
;

CREATE INDEX IXFK_cliente_pais ON cliente (id_pais ASC)
;

CREATE INDEX IXFK_cliente_tipo_cliente ON cliente (id_tipo_cliente ASC)
;

CREATE INDEX IXFK_cliente_tipo_documento ON cliente (id_tipo_documento ASC)
;

CREATE INDEX IXFK_cliente_ubicacion ON cliente (id_ubicacion ASC)
;

ALTER TABLE Formas_pago ADD CONSTRAINT PK_Table1
	PRIMARY KEY (id_forma_pago)
;

ALTER TABLE Giros ADD CONSTRAINT PK_giro
	PRIMARY KEY (id_giro)
;

CREATE INDEX IXFK_Giros_cliente ON Giros (id_cliente ASC)
;

CREATE INDEX "IXFK_Giros_Negociacion " ON Giros ()
;

CREATE INDEX IXFK_Giros_pais ON Giros ()
;

ALTER TABLE Locutorio ADD CONSTRAINT PK_Locutorio
	PRIMARY KEY (id_locutorio)
;

CREATE INDEX IXFK_Locutorio_Giros ON Locutorio (id_giro ASC)
;

ALTER TABLE "Negociacion " ADD CONSTRAINT PK_Negociacion
	PRIMARY KEY (Id_negociacion)
;

CREATE INDEX "IXFK_Negociacion _pais" ON "Negociacion " (id_pais ASC)
;

ALTER TABLE pais ADD CONSTRAINT PK_pais
	PRIMARY KEY (UPS_pais)
;

CREATE INDEX IXFK_pais_Giros ON pais ()
;

CREATE INDEX "IXFK_pais_Negociacion " ON pais (Id_negociacion ASC)
;

ALTER TABLE tipo_cliente ADD CONSTRAINT PK_tipo_cliente
	PRIMARY KEY (id_tipo_cliente)
;

ALTER TABLE tipo_documento ADD CONSTRAINT PK_tipo_documento
	PRIMARY KEY (id_tipo_documento)
;

CREATE INDEX IXFK_tipo_documento_cliente ON tipo_documento (id_cliente ASC)
;

ALTER TABLE ubicacion ADD CONSTRAINT PK_ubicacion
	PRIMARY KEY (id_ubicacion)
;

CREATE INDEX IXFK_ubicacion_cliente ON ubicacion (id_cliente ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE biometria ADD CONSTRAINT FK_biometria_cliente
	FOREIGN KEY (id_cliente) REFERENCES cliente (id_cliente) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE cliente ADD CONSTRAINT FK_cliente_pais
	FOREIGN KEY (id_pais) REFERENCES pais (UPS_pais) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE cliente ADD CONSTRAINT FK_cliente_tipo_cliente
	FOREIGN KEY (id_tipo_cliente) REFERENCES tipo_cliente (id_tipo_cliente) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE cliente ADD CONSTRAINT FK_cliente_tipo_documento
	FOREIGN KEY (id_tipo_documento) REFERENCES tipo_documento (id_tipo_documento) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE Giros ADD CONSTRAINT FK_Giros_cliente
	FOREIGN KEY (id_cliente) REFERENCES cliente (id_cliente) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE Locutorio ADD CONSTRAINT FK_Locutorio_Giros
	FOREIGN KEY (id_giro) REFERENCES Giros (id_giro) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Negociacion " ADD CONSTRAINT "FK_Negociacion _pais"
	FOREIGN KEY (id_pais) REFERENCES pais (UPS_pais) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE ubicacion ADD CONSTRAINT FK_ubicacion_cliente
	FOREIGN KEY (id_cliente) REFERENCES cliente (id_cliente) ON DELETE Restrict ON UPDATE Restrict
;
