/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 24-feb.-2020 8:33:03 p. m. 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS biometria CASCADE
;

DROP TABLE IF EXISTS cliente CASCADE
;

DROP TABLE IF EXISTS Giros CASCADE
;

DROP TABLE IF EXISTS pais CASCADE
;

DROP TABLE IF EXISTS tipo_cliente CASCADE
;

DROP TABLE IF EXISTS tipo_documento CASCADE
;

DROP TABLE IF EXISTS ubicacion CASCADE
;

/* Drop Sequences */

DROP SEQUENCE  IF EXISTS  biometria_set  CASCADE
;

/* Create Sequences */

serial start 0
;

/* Create Tables */

CREATE TABLE biometria
(
	huella_digital_1 bytea NULL,
	huella_digital_2 bytea NULL,
	id_biometria numeric(20) NOT NULL,
	id_cliente varchar(5) NULL
)
;

CREATE TABLE cliente
(
	id_cliente varchar(5) NOT NULL,
	nombre varchar(30) NULL,
	apellidos varchar(30) NULL,
	razon_social varchar(30) NULL,
	id_tipo_documento varchar(5) NULL,
	id_biometria numeric(20) NULL,
	id_pais varchar(50) NULL,
	id_tipo_cliente varchar(50) NULL,
	id_ubicacion varchar(50) NULL,
	id_giro varchar(50) NULL
)
;

CREATE TABLE Giros
(
	id_giro varchar(50) NOT NULL,
	pais_origen varchar(50) NULL,
	pais_llegada varchar(50) NULL,
	Valor_giro money NULL,
	id_cliente varchar(50) NULL,
	id_pais varchar(50) NULL
)
;

CREATE TABLE pais
(
	nombre varchar(50) NULL,
	gentilicio varchar(50) NULL,
	id_pais varchar(50) NOT NULL,
	id_giro varchar(50) NULL
)
;

CREATE TABLE tipo_cliente
(
	id_tipo_cliente varchar(50) NOT NULL,
	nombre varchar(50) NULL
)
;

CREATE TABLE tipo_documento
(
	id_tipo_documento varchar(5) NOT NULL,
	nombre_documento varchar(50) NULL,
	id_cliente varchar(5) NULL
)
;

CREATE TABLE ubicacion
(
	id_ubicacion varchar(50) NOT NULL,
	nombre varchar(50) NULL,
	id_cliente varchar(5) NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE biometria ADD CONSTRAINT PK_Table1
	PRIMARY KEY (id_biometria)
;

CREATE INDEX IXFK_biometria_cliente ON biometria (id_cliente ASC)
;

ALTER TABLE cliente ADD CONSTRAINT PK_cliente
	PRIMARY KEY (id_cliente)
;

CREATE INDEX IXFK_cliente_biometria ON cliente (id_biometria ASC)
;

CREATE INDEX IXFK_cliente_cliente ON cliente (id_cliente ASC)
;

CREATE INDEX IXFK_cliente_Giros ON cliente (id_giro ASC)
;

CREATE INDEX IXFK_cliente_pais ON cliente (id_pais ASC)
;

CREATE INDEX IXFK_cliente_tipo_cliente ON cliente (id_tipo_cliente ASC)
;

CREATE INDEX IXFK_cliente_tipo_documento ON cliente (id_tipo_documento ASC)
;

CREATE INDEX IXFK_cliente_ubicacion ON cliente (id_ubicacion ASC)
;

ALTER TABLE Giros ADD CONSTRAINT PK_Table1
	PRIMARY KEY (id_giro)
;

CREATE INDEX IXFK_Giros_cliente ON Giros (id_cliente ASC)
;

CREATE INDEX IXFK_Giros_pais ON Giros (id_pais ASC)
;

ALTER TABLE pais ADD CONSTRAINT PK_pais
	PRIMARY KEY (id_pais)
;

CREATE INDEX IXFK_pais_Giros ON pais (id_giro ASC)
;

ALTER TABLE tipo_cliente ADD CONSTRAINT PK_Table1
	PRIMARY KEY (id_tipo_cliente)
;

ALTER TABLE tipo_documento ADD CONSTRAINT PK_Table1
	PRIMARY KEY (id_tipo_documento)
;

CREATE INDEX IXFK_tipo_documento_cliente ON tipo_documento (id_cliente ASC)
;

ALTER TABLE ubicacion ADD CONSTRAINT PK_Table1
	PRIMARY KEY (id_ubicacion)
;

CREATE INDEX IXFK_ubicacion_cliente ON ubicacion (id_cliente ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE biometria ADD CONSTRAINT FK_biometria_cliente
	FOREIGN KEY (id_cliente) REFERENCES cliente (id_cliente) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE cliente ADD CONSTRAINT FK_cliente_biometria
	FOREIGN KEY (id_biometria) REFERENCES  () ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE cliente ADD CONSTRAINT FK_cliente_cliente
	FOREIGN KEY (id_cliente) REFERENCES  () ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE cliente ADD CONSTRAINT FK_cliente_Giros
	FOREIGN KEY (id_giro) REFERENCES  () ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE cliente ADD CONSTRAINT FK_cliente_pais
	FOREIGN KEY (id_pais) REFERENCES pais (id_pais) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE cliente ADD CONSTRAINT FK_cliente_tipo_cliente
	FOREIGN KEY (id_tipo_cliente) REFERENCES tipo_cliente (id_tipo_cliente) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE cliente ADD CONSTRAINT FK_cliente_tipo_documento
	FOREIGN KEY (id_tipo_documento) REFERENCES tipo_documento (id_tipo_documento) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE cliente ADD CONSTRAINT FK_cliente_ubicacion
	FOREIGN KEY (id_ubicacion) REFERENCES  () ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE Giros ADD CONSTRAINT FK_Giros_cliente
	FOREIGN KEY (id_cliente) REFERENCES cliente (id_cliente) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE Giros ADD CONSTRAINT FK_Giros_pais
	FOREIGN KEY (id_pais) REFERENCES pais (id_pais) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE pais ADD CONSTRAINT FK_pais_Giros
	FOREIGN KEY (id_giro) REFERENCES  () ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE tipo_documento ADD CONSTRAINT FK_tipo_documento_cliente
	FOREIGN KEY (id_cliente) REFERENCES  () ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE ubicacion ADD CONSTRAINT FK_ubicacion_cliente
	FOREIGN KEY (id_cliente) REFERENCES cliente (id_cliente) ON DELETE Restrict ON UPDATE Restrict
;
